### ISSUE TITLE
Google colab issue

### ISSUE THREAD

**Issue by JasperBalmes** [ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example#1]
I cant seem to make this code run like the lecture video. Im not sure how to follow along the lesson with out the code . 

I also get a warning when I try to run the file because this notebook is not authorized by google 

This is the traceback I get on google colab when I click the play button on the 2nd line of code: 
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-2fa7713006b7> in <module>()
      1 sales = pd.read_csv(
      2     'data/sales_data.csv',
----> 3     parse_dates=['Date'])

4 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1889         kwds["usecols"] = self.usecols
   1890 
-> 1891         self._reader = parsers.TextReader(src, **kwds)
   1892         self.unnamed_cols = self._reader.unnamed_cols
   1893 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File data/sales_data.csv does not exist: 'data/sales_data.csv'

**Comment by santiagobasulto** [comment]
You need to upload the `csv` file to your google account, and possibly change the path `data/sales_data.csv` to something else. Check the `data` directory in this repo.
