### ISSUE TITLE
Exercises_2.ipynb sql code cannot import data

### ISSUE THREAD

**Issue by solomonmichael** [ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example#14]
Was getting this error, fixed it by swapping the / for a forward slash, or even deleting "data/" alltogether
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-3-e7bd0fe9801d> in <module>()
----> 1 conn = sqlite3.connect('data/sakila.db')
      2 
      3 df = pd.read_sql('''
      4     SELECT
      5         rental.rental_id, rental.rental_date, rental.return_date,

OperationalError: unable to open database file

Now getting a new error - same error when I try using Mysql directly instead of Colab:
----------------------------------------------------------------------
OperationalError: no such table: rental

Also in Mysql when I just use the SQL, seeing another error saying that the syntax around the SQL portion is incorrect. 
---------------------------------------------------------------------------
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '== customer.customer_id
    INNER JOIN inventory ON rental.inventory_id == inven' at line 10

Can't figure this out to save my life.

**Comment by santiagobasulto** [comment]
If you didn't download the `data/sakila.db` file, then it will fail to load it. And then, the issue with the SQL syntax is that the comparison is one single equal sign: `ON rental.inventory_id = inven` instead of `ON rental.inventory_id == inven`
