### ISSUE TITLE
practice

### ISSUE THREAD

**Issue by hortusEdenis** [ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example#18]
how do I open the practice files to work on them? every time I press open in GitHub desktop it just prompts me to download GitHub again

**Comment by Preludius** [comment]
I have exactly the same issue - I have just logged into GitHub and I'm trying to do exercises and it won't allow me to  it the code when it is showing "type your code here" - any advice?

**Comment by santiagobasulto** [comment]
Try directly on mybinder: https://mybinder.org/
