### ISSUE TITLE
Cannot read data file

### ISSUE THREAD

**Issue by LujewTL** [ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example#19]
I can't edit any of the coding textboxes within github, and when I open the code in google colab, I can't read the data file.
![problem](https://user-images.githubusercontent.com/98063671/150239734-57b8ebc4-22ac-44bb-9ea9-027462bfdcb8.png)

**Comment by santiagobasulto** [comment]
You seem to be working on Google Colab, which I think doesn't offer a hard drive, so it can't find the file under the `data/` directory. Try mybinder instead: https://mybinder.org/
