### ISSUE TITLE
Can't read data file and upload course file

### ISSUE THREAD

**Issue by Hassona629** [ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example#20]
I'm a beginner in the field of coding and I can't follow the course videos. At the first lecture, I'm trying to retrieve the sales_data.csv file but it's not working! 

How I can upload the course file into Jupyter Notebook?

![image](https://user-images.githubusercontent.com/65969692/152029517-94b1d927-e035-4f90-a303-9008716616ec.png)
![screencapture-localhost-8888-notebooks-Untitled-ipynb-2022-02-01-12_33_55](https://user-images.githubusercontent.com/65969692/152029668-a728615d-74ac-47e4-a3cb-0a1d24d9aa96.png)

**Comment by santiagobasulto** [comment]
The file is in the repo: https://github.com/ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example/blob/master/data/sales_data.csv

Did you clone the whole repo or downloaded just that notebook? I recommend you to use mybinder and run the whole project at once.
