### ISSUE TITLE
Exercise 1 incorrect code?

### ISSUE THREAD

**Issue by thepaperrose** [ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example#3]
For the Question: How many sales with more than 500 in Revenue were made by men?
The answer given is: sales.loc[(sales['Customer_Gender'] == 'M') & (sales['Revenue'] == 500)].shape[0]

Question asks for MORE than 500. Shouldn't answer be: sales.loc[(sales['Customer_Gender'] == 'M') & (sales['Revenue'] **>=** 500)].shape[0]

**Comment by OlegTys** [comment]
">=" is more or equal. Exercise requires more than 500.

Hence instead of answer with "==" there should be ">".

**Comment by miriamokolosi** [comment]
I cannot type in my codes for the exercise

**Comment by santiagobasulto** [comment]
Thank you, we'll fix it.
