### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by gndoshi** [ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example#8]
Hi, I'm trying to follow along using Google Colab but the data doesn't open - it says that there is no such file. How can I use the data used in these lectures to follow along? Please help me.

**Comment by afifaboubakr** [comment]
Hi
just change the path in the code and make sure you import the file to the
online folder
warm regards .

Le dim. 2 mai 2021 à 11:39, Gautam Doshi ***@***.***> a
écrit :

**Comment by sairatabassum** [comment]
> Hi, I'm trying to follow along using Google Colab but the data doesn't open - it says that there is no such file. How can I use the data used in these lectures to follow along? Please help me.
Hello,
Click on `view raw   `and copy the link, pass it to the read_csv(),  in this way you can easily open the data.

```
import pandas as pd
sales = pd.read_csv('https://raw.githubusercontent.com/ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example/master/data/sales_data.csv')
```

for more information check this out [Ways to import CSV files in Google Colab
](https://www.geeksforgeeks.org/ways-to-import-csv-files-in-google-colab/)

In jupyter notebook , save the data folder in the same directory where  you are currently working in.

**Comment by sairatabassum** [comment]
Hello,
Click on `view raw   `and copy the link, pass it to the read_csv(),  in this way you can easily open the data.

```
import pandas as pd
sales = pd.read_csv('https://raw.githubusercontent.com/ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example/master/data/sales_data.csv')
sales
```

for more information check this out [Ways to import CSV files in Google Colab
](https://www.geeksforgeeks.org/ways-to-import-csv-files-in-google-colab/)

In jupyter notebook , save the data folder in the same directory where  you are currently working in.

**Comment by gndoshi** [comment]
Thank you guys!
